Blog app - Add forms
SabiMantock/blog-app pull request #7
Opened 2023-04-22 21:21 UTC by SabiMantock

In this milestone, the Project Requirements were to;

- [ ] Create a method called current_user in your ApplicationController to make current user data available to all controllers.
- [ ] Create forms to perform the following functions:
   - Creates a Post on behalf of the current_user (use the method that you created in your ApplicationController).
   - Create a comment on behalf of the current_user (use the method that you created in your ApplicationController).
 - [ ] Allow Users to add likes to Posts.

2023-04-22 22:41 UTC, Felix45 requested changes
Hi @SabiMantock , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966" width="375px" />

## Highlights :heavy_check_mark: 
- [x] Add post forms added correctly :white_check_mark: 
- [x] Git flow is used correctly :white_check_mark:  
- [x] Repository has a professional readme file :white_check_mark:  
- [x]  Pull request has a descriptive title and summary :white_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-22 22:41 UTC, Felix45 commented on app/controllers/comments_controller.rb
> +end
- [ Required ] Good job adding the comments controller and the `create` action, however, your controller ought to also have a `new` method that leads to the `new comment` form similar to the one you've created for posts in the `posts_controller`. Please see the screenshot below and rectify this.

## Project requirements
![Screenshot from 2023-04-23 01-31-21](https://user-images.githubusercontent.com/16392046/233810535-4a49dee5-cad7-4e04-8a9e-faf1009ce7c3.png)

2023-04-22 22:41 UTC, Felix45 commented on config/routes.rb
> +  post 'comments/:post_id', to: 'comments#create'
- [ Required ] I think it would be better if you add the following routes to your `routes.rb` file which can be used to add comments to your posts, currently i'm not able to add a comment to a post using the available routes from the browser. 

  - `GET /posts/:post_id/comments/new(.:format) comments#new`  leads to the create new comment form
  - `POST /posts/:post_id/comments(.:format) comments#create` saves a comment on a post to the database 

- [ Required ] I think it would be better if you add a form in the `views/comments/new.html.erb` file which accepts input for creating comments on a post, currently, there is no view file in your project that has a form for doing this.

2023-04-22 22:41 UTC, Felix45 commented on config/routes.rb
> +  post 'likes/:post_id', to: 'likes#create'
- [Required] I think it would be better if you refactor this route to be like this `POST /posts/:post_id/likes(.:format) likes#create`, Currently, this route can not be used to retrieve the `post_id` param which is needed for the logic of your `likes#create` controller method to work correctly.

2023-04-22 22:41 UTC, Felix45 commented on app/views/users/show.html.erb
> +        <span>, Likes: <%= "#{post.likes_counter || 0}" %></span>
- [ Required ] I think it would be better if you add a `Like` button/form to your posts that can be used to add a like to a post, currently, I am not able to add a like to a post from the browser.

## Project requirements
![Screenshot from 2023-04-23 01-31-21](https://user-images.githubusercontent.com/16392046/233810435-00707e16-ca7d-463a-bf1c-7196c527a7d8.png)

2023-04-26 01:49 UTC, HAMMAS-SALEEM reviewed
# Invalid Submission :red_circle:

![invalid-submission](https://user-images.githubusercontent.com/93039359/221218445-05489541-f840-492c-878e-0587cc2b3702.gif)

## Hey @SabiMantock :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements

Good job on implementing some of the requirements but I cannot proceed review of your pull request because there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 01:49 UTC, HAMMAS-SALEEM commented on app/controllers/comments_controller.rb
> +
- [ ] It would be very nice if you make a new pull request and submit it for a review because this pull request was for previous week and it is not approved so because of that kindly make a new pull request and submit that for the review 👍

2023-04-28 09:08 UTC, closed without merging