Blog app - Add forms
SabiMantock/blog-app pull request #8
Opened 2023-04-28 09:07 UTC by SabiMantock

In this milestone, the Project Requirements were to;

- [x] Create a method called current_user in your ApplicationController to make current user data available to all controllers.
- [x] Create forms to perform the following functions:
   - Creates a Post on behalf of the current_user (use the method that you created in your ApplicationController).
   - Create a comment on behalf of the current_user (use the method that you created in your ApplicationController).
 - [x] Allow Users to add likes to Posts.

2023-04-28 09:27 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @SabiMantock,

Good job so far!
✔️ Likes can be created
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 09:27 UTC, TedLivist commented on app/views/posts/index.html.erb
> + <a href="/posts/new" class="btn btn-outline-secondary rounded-pill m-2 text-decoration-none">Create new post</a>
- [ ] Kindly fix your route here. It is incorrect. If you take a look at your routes file, there is no `new` post route

  ![image](https://user-images.githubusercontent.com/36542986/235108864-1122ebaa-ecfd-4390-858a-ff5534c1fbed.png)

2023-04-28 09:27 UTC, TedLivist commented on app/views/posts/show.html.erb
> +  </div>
- [ ] Comments are not being created when I add them. Kindly look into that. I think this may have to do with your `url` attribute on line 30.

  ![image](https://user-images.githubusercontent.com/36542986/235110252-56283730-ed65-46e2-9364-11219988c54b.png)

2023-04-28 11:35 UTC, DammyShittu approved these changes
Hi @SabiMantock,

## APPROVED 🟢

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 11:35 UTC, merged

2023-06-19 20:20 UTC, Ismailco reviewed
### Hi @SabiMantock, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._